package it.maicol07.gamerlogue.ui.views.game

import at.released.igdbclient.apicalypse.ApicalypseQueryBuilder
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

/** Pins the fields consumed by the detail screen, including image and related-game metadata. */
class GameDetailFieldsTest : StringSpec({
    "the detail query asks for exactly the fields the screen renders" {
        val expected = setOf(
            "age_ratings.category",
            "age_ratings.rating",
            "age_ratings.rating_cover_url",
            "aggregated_rating",
            "aggregated_rating_count",
            "alternative_names.comment",
            "alternative_names.name",
            "artworks.image_id",
            "bundles.cover.image_id",
            "bundles.first_release_date",
            "bundles.id",
            "bundles.name",
            "bundles.rating",
            "collections.games.cover.image_id",
            "collections.games.first_release_date",
            "collections.games.id",
            "collections.games.name",
            "collections.games.rating",
            "collections.name",
            "cover.image_id",
            "dlcs.cover.image_id",
            "dlcs.first_release_date",
            "dlcs.id",
            "dlcs.name",
            "dlcs.rating",
            "expanded_games.cover.image_id",
            "expanded_games.first_release_date",
            "expanded_games.id",
            "expanded_games.name",
            "expanded_games.rating",
            "expansions.cover.image_id",
            "expansions.first_release_date",
            "expansions.id",
            "expansions.name",
            "expansions.rating",
            "first_release_date",
            "franchise.name",
            "franchises.name",
            "game_engines.name",
            "game_modes.name",
            "game_status.status",
            "game_type.type",
            "genres.name",
            "involved_companies.company.name",
            "involved_companies.developer",
            "involved_companies.publisher",
            "keywords.name",
            "language_supports.language.name",
            "language_supports.language_support_type.name",
            "multiplayer_modes.campaigncoop",
            "multiplayer_modes.dropin",
            "multiplayer_modes.lancoop",
            "multiplayer_modes.offlinecoop",
            "multiplayer_modes.offlinecoopmax",
            "multiplayer_modes.offlinemax",
            "multiplayer_modes.onlinecoop",
            "multiplayer_modes.onlinecoopmax",
            "multiplayer_modes.onlinemax",
            "multiplayer_modes.splitscreen",
            "name",
            "parent_game.cover.image_id",
            "parent_game.first_release_date",
            "parent_game.id",
            "parent_game.name",
            "platforms.id",
            "platforms.name",
            "platforms.platform_logo.image_id",
            "player_perspectives.name",
            "ports.cover.image_id",
            "ports.first_release_date",
            "ports.id",
            "ports.name",
            "ports.rating",
            "rating",
            "rating_count",
            "release_dates.date",
            "release_dates.platform",
            "release_dates.release_region",
            "release_dates.status.name",
            "remakes.cover.image_id",
            "remakes.first_release_date",
            "remakes.id",
            "remakes.name",
            "remakes.rating",
            "remasters.cover.image_id",
            "remasters.first_release_date",
            "remasters.id",
            "remasters.name",
            "remasters.rating",
            "screenshots.image_id",
            "similar_games.cover.image_id",
            "similar_games.first_release_date",
            "similar_games.id",
            "similar_games.name",
            "similar_games.rating",
            "standalone_expansions.cover.image_id",
            "standalone_expansions.first_release_date",
            "standalone_expansions.id",
            "standalone_expansions.name",
            "standalone_expansions.rating",
            "storyline",
            "summary",
            "themes.name",
            "url",
            "version_parent.cover.image_id",
            "version_parent.first_release_date",
            "version_parent.id",
            "version_parent.name",
            "videos.name",
            "videos.video_id",
            "websites.category",
            "websites.trusted",
            "websites.url",
        )

        // The builder emits the short query form.
        val query = ApicalypseQueryBuilder().fields(*DetailFields.toTypedArray()).build().toString()
        val actual = query.removePrefix("f ").removeSuffix(";").split(",").map { it.trim() }.toSet()

        // Split assertions: the two diffs read better than one 100-element mismatch.
        (actual - expected) shouldBe emptySet()
        (expected - actual) shouldBe emptySet()
    }
})
